version: "2"
services:
  app:
    container_name: CRUD
    restart: always
    build: .
    ports:
    - "4000:4000"
    links:
    - mongo
  mongo:
    container_name: userCrud
    image: mongo
    ports:
    - "27017:27017"
